name: Terraform GCP Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      action:
        description: "Terraform action to run (plan, apply, destroy)"
        required: true
        default: "plan"
        type: choice
        options:
          - plan
          - apply
          - destroy
      branch:
        description: "Git branch to run workflow from"
        required: false
        default: "main"

jobs:
  terr
